### PR TITLE
use absolute dir for tmp

### PR DESCRIPTION
**Pull request by chaoky**
build was failing with
```
FileNotFoundError: [Errno 2] No such file or directory: 'tmp/module_file.module'
```

### CODE REVIEW

**Comment by chaoky** [comment]
somewhat hard to catch, since changing the script does not trigger a rebuild

**Comment by CrazyChaoz** [comment]
changing /tmp to a local tmp folder is meant to fix issues with nix on macos, no rebuild being triggered on changes is a different issue that i should probably address at some point

**Comment by chaoky** [comment]
oh sorry, I see that issue now, what about creating the "tmp" dir before using it?

**Comment by chaoky** [comment]
https://github.com/CrazyChaoz/gradle-dot-nix/pull/3 works for me, thanks!

**Pull request closed without merging**
